language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules

notifications:
  # 钉钉机器人消息推送部署结果
  webhooks:
    urls:
      - https://oapi.dingtalk.com/robot/send?access_token=${NOTIFY_TOKEN} # NOTIFY_TOKEN在Travis中配置的
    on_success: always
    on_failure: always

before_install:
  - echo 安装hexo相关环境...

install:
  - npm install

before_script:
  - echo 正在清空缓存静态文件...
  - hexo clean                      
  - echo 正在生成静态文件...
  - hexo g                          
  - cd ./public
  - ls -l

script:
  - echo 开始部署...
  - git init
  - git config --global user.name "${GH_username}" 
  - git config --global user.email "${GH_useremail}" 
  - git add ./
  - git commit -m "update"
  - git push --force --quiet "https://${GitHubKEY}@${GH_REF}" master:master  # GitHubKEY在Travis中配置的

after_script:
  - echo 部署完成！

branches:
  only:
    - master
env:
  global:
    - GH_REF: github.com/akun2014/akun2014.github.io.git                   # 设置 github 项目仓库地址
    - GH_username: akun2014                                               # 设置 github 用户名           
    - GH_useremail: e-gk@qq.com                                            # 设置 github 绑定邮箱地址
