# ---------------------------------------------------------------
#   Site Information And Theme Configuration Settings
#   language: zh-CN
# ---------------------------------------------------------------

## menu
menu:
- page: home
  url: /
  icon:
- page: Java
  url: /categories/java/
  icon:
- page: DevOps
  url: /categories/devops/
  icon:
- page: 大数据
  url: /categories/bigdata/
  icon:
- page: 分布式系统
  url: /categories/distributed-system/
  icon:
- page: 操作系统
  url: /categories/os/
  icon:
- page: 时间轴
  url: /archives/
  icon:

## favicon
favicon: /favicon.ico

## Feed
rss: /atom.xml

## Carousel
carousel:
  img: './img/head-img.png'
  url: 'https://github.com/akun2014/coolkaka'

# 各个小工具的设置

## widgets
widgets:
  - search
  - notification
  - social
  - category
  - archive
  - tagcloud
  - friends


## 搜索
jsonContent:
  searchLocal: true
  searchGoogle: false
  posts:
    title: true
    text: true
    content: true
    categories: true
    tags: true

## 网站公告设置
notification: |-
            <p>
               <a href="https://www.coolkaka.cn/2019/08/12/Home/">菜鸟的成神之路</a>
            </p>

## 社交设置
social:
 - name: Github
   icon: git
   href: //github.com/akun2014
 - name: 邮箱
   icon: envelope-o
   href: mailto:e-gk@qq.com
 - name: 微信
   icon: weixin
   href: /
 - name: RSS
   icon: feed
   href: /atom.xml

## 文章分类设置
cate_config:
   show_count: true
   show_current: true

## 文章归档设置
arch_config:
   type: 'monthly'
   format: 'YYYY年MM月'
   show_count: true
   order: -1

## 标签云设置
tagcloud:
  tag3d: false
  textColour: '#444'
  outlineMethod: 'block'
  outlineColour: '#FFDAB9'
  interval: 30
  freezeActive: true
  frontSelect: true
  reverse: true
  wheelZoom: false

## 友链设置
links:
  - 芋道源码: http://www.iocoder.cn/
  - 程序员DD: http://blog.didispace.com/
  - hollis blog: https://www.hollischuang.com/

# 主题自定义个性化配置

## 网站宣传语
branding: 念念不忘、必有回响

## 设置banner背景图片
banner:
    img: http://snippet.shenliyang.com/img/banner.jpg

## 首页列表底部面板
homePanel: true

## 缩略图自定义随机图片
defaultImgs:
  -

## 截取文章首页描述字数
excerptLength: 120

## 是否开启文章目录
toc: true

## 代码高亮配置
highlightTheme:

## bootstrap配置
bootstrap:

## ICON配置
fontAwesome:

## 文章过期提醒功能
warning:
  days: 300
  text: '本文于%d天之前发表，文中内容可能已经过时。'

## 文章内声明
declaration:
  enable: true
  title: '转载声明'
  tip: |-
      商业转载请联系作者获得授权,非商业转载请注明出处 © <a href="https://coolkaka.cn/" target="_blank">coolkaka</a>

## 文章打赏
reward:
  alipay: ''
  wepay: ''
  tip: 赞赏是不耍流氓的鼓励

## 主题评论

## Valine评论
valine:
   enable: false
   appId: xOKV9J4UeQAtVkvnJC7Kq2Jn-gzGzoHsz
   appKey: erIpQac4azoCmgfBB7Dl9maa
   placeholder: 说点什么吧
   notify: false
   verify: true
   avatar: mm
   meta: nick,mail,link
   pageSize: 10

## 不使用的评论系统
changyan:
  enable: false
livere:
  enable: false
## Gitalk评论
gitalk:
   enable: true
   clientID: a4caee55785129655f40
   clientSecret: 960c3d3af8f5ffe86ce44231a5450fc4167c65e9
   repo: bloggittalk
   owner: 'akun2014'
   admin: ['akun2014']
   perPage: 10
   distractionFreeMode: false
disqus:
  enable: false
gitment:
  enable: false
uyan:
  enable: false

## 网站访客统计
visit_counter:
   site: true
   page: true

## 网站访问统计分析

### 网盟CNZZ统计 1263868967
cnzz_analytics: 

### 百度统计
baidu_analytics: d945b6e6aeb37f6ff2e7b309ea2af4f2

### 谷歌统计
google_analytics:

### 腾讯分析
tencent_analytics:

### 百度站点认证
baidu_site_verification:

### 百度自动推送
baidu_push: false

#网站主题配置
since: 2019
robot: 'all' ### 控制搜索引擎的抓取和索引编制行为，默认为all
version: 1.2.3
